proxy:
  image: nginx:1.7
  ports:
   - '8085:80'
  links:
   - server
   - client
  volumes:
   - ./devops/:/etc/nginx/conf.d/

server:
  build: server/.
  ports:
   - '5000:5000'
  volumes:
   - ./server/:/var/www/ia
  links:
  - postgres
  env_file: ./environment-variables.env
  command: python3 /var/www/ia/api.py


postgres:
  image: postgres
  ports:
  - '5432:5432'
  volumes:
  - ./postgres-data:/var/lib/postgresql/data

client:
  build: .
  ports:
   - '8080:80'
  volumes:
   - ./:/var/www/client
  command: yarn start
