"""empty message

Revision ID: 2ddcf39e4d17
Revises:
Create Date: 2018-12-31 19:03:37.288837

"""
from alembic import op
import sqlalchemy as sa
import models


# revision identifiers, used by Alembic.
revision = '2ddcf39e4d17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_turn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turn', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('square',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('nb', sa.Integer(), nullable=True),
    sa.Column('species', models.Square.Species(name='species_values'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('square')
    op.drop_table('player_turn')
    # ### end Alembic commands ###
