"""empty message

Revision ID: 35e160139f5d
Revises: 
Create Date: 2019-01-06 14:03:52.355946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35e160139f5d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_turn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turn', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('square',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('nb', sa.Integer(), nullable=True),
    sa.Column('species', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('square')
    op.drop_table('player_turn')
    # ### end Alembic commands ###
